baseURL = '/'
languageCode = 'en-us'
theme = "hello-friend-ng"


PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate = 10
#rssLimit  = 10  # Maximum number of items in the RSS feed.
#copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = false
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"


  # Enable theme toggle
  # 
  # This options enables the theme toggle for the theme. 
  # Per default, this option is off. 
  # The theme is respecting the prefers-color-scheme of the operating systeme. 
  # With this option on, the page user is able to set the scheme he wants. 
  enableThemeToggle = true

  # Global language menu
  #
  # Enables the global language menu.
  #
  enableGlobalLanguageMenu = true

[params.footer]
    trademark = true
    rss = false
    copyright = true
    author = false

    topText = []
    bottomText = [
      "Powered by <a href=\"https://www.geektweax.com\">The Geek Tweax</a>",
#      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
     logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
     logoCursorAnimate  = "1s"

# Uncomment this if you want a portrait on your start page
#
# [params.portrait]
#   path     = "/img/image.jpg"
#   alt      = "Portrait"
#   maxWidth = "50px"


# Social icons
#  [[params.social]]
#    name = "twitter"
#    url  = "https://twitter.com/"
#
#  [[params.social]]
#    name = "email"
#    url  = "mailto:nobody@example.com"
#
#  [[params.social]]
#    name = "github"
#    url  = "https://github.com/"
#
#  [[params.social]]
#    name = "linkedin"
#    url  = "https://www.linkedin.com/"
#
#  [[params.social]]
#    name = "stackoverflow"
#    url  = "https://www.stackoverflow.com/"

[languages]
  [languages.en]
    subtitle  = "Coming Soon!"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    title = 'Coming Soon!'

  [languages.fr]
    subtitle  = "Bientôt disponible!"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    title = 'Bientôt disponible!'

  [languages.ar]
    subtitle  = "!قريبا"
    weight    = 3
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    title = '!قريبا'

[menu]
  [[menu.main]]
#    identifier = "about"
#    name       = "About"
#    url        = "about/"
  [[menu.main]]
#    identifier = "posts"
#    name       = "Posts"
#    url        = "posts/"
